/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DBSearch;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Nadeesha
 */
public class InventoryReceive extends javax.swing.JFrame {

    /**
     * Creates new form InventoryReceive
     */
    public InventoryReceive() {
        initComponents();
        
        SearchMid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MatIdCMB = new javax.swing.JComboBox<>();
        StockTF = new javax.swing.JTextField();
        NewQtyTF = new javax.swing.JTextField();
        NewStockTF = new javax.swing.JTextField();
        UpdateBTN = new javax.swing.JButton();
        CalBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 255, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Inventory - Receive");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 30, 382, 60);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Material ID :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 150, 124, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Stock at hand :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 280, 143, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("New Qty :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 360, 110, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("New Stock :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 430, 117, 28);

        MatIdCMB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(MatIdCMB);
        MatIdCMB.setBounds(220, 150, 160, 40);

        StockTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(StockTF);
        StockTF.setBounds(270, 280, 180, 40);

        NewQtyTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(NewQtyTF);
        NewQtyTF.setBounds(220, 360, 130, 30);

        NewStockTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(NewStockTF);
        NewStockTF.setBounds(240, 420, 150, 40);

        UpdateBTN.setBackground(new java.awt.Color(0, 0, 0));
        UpdateBTN.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        UpdateBTN.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBTN.setText("Update");
        UpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTNActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateBTN);
        UpdateBTN.setBounds(400, 530, 130, 40);

        CalBTN.setBackground(new java.awt.Color(0, 0, 0));
        CalBTN.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        CalBTN.setForeground(new java.awt.Color(255, 255, 255));
        CalBTN.setText("Calculate");
        CalBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalBTNActionPerformed(evt);
            }
        });
        jPanel1.add(CalBTN);
        CalBTN.setBounds(70, 220, 130, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IMG-20190821-WA0053-2.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 340, 450, 170);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(560, 530, 90, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalBTNActionPerformed
        // TODO add your handling code here:
        try{
           
            ResultSet rs = new DBSearch().SearchBom("Select SQty From Material WHERE MatId = '"+MatIdCMB.getSelectedItem()+"'");
            while(rs.next()) {
                StockTF.setText(rs.getString("SQty"));
        } 
         }                                         
            catch(Exception e){
                e.printStackTrace();
        }
    }//GEN-LAST:event_CalBTNActionPerformed

    private void UpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTNActionPerformed
        // TODO add your handling code here:
        int NewQty = Integer.parseInt(NewQtyTF.getText().toString());
        int Qty = Integer.parseInt(StockTF.getText().toString());
        
        NStock(NewQty, Qty);
        try{
            String NewStock = NewStockTF.getText();
            int res = DBSearch.getMquantity("Update Material SET SQty= '"+NewStock+"' WHERE MatId = '"+MatIdCMB.getSelectedItem()+"'");
            if(res>0) {
                JOptionPane.showMessageDialog(null,"Successfully Updated.");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
    }                                         

    void NStock(int p, int q)
    {
        int t = p + q;
        NewStockTF.setText(t + "");
    }
    
    public void SearchMid(){
        
        try{
           
            ResultSet rs = new DBSearch().SearchMid("Select * From Material");
            
            while(rs.next()) {
                MatIdCMB.addItem(rs.getString("MatId"));
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_UpdateBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        InventoryReceive.getFrames()[1].dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryReceive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryReceive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryReceive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryReceive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryReceive().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalBTN;
    private javax.swing.JComboBox<String> MatIdCMB;
    private javax.swing.JTextField NewQtyTF;
    private javax.swing.JTextField NewStockTF;
    private javax.swing.JTextField StockTF;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
