/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DBSearch;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nadeesha
 */
public class ItemCosting extends javax.swing.JFrame {

    /**
     * Creates new form ItemCosting
     */
    public ItemCosting() {
        initComponents();
        
        SearchCode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        IcodeCMB = new javax.swing.JComboBox<>();
        BomIdCMB = new javax.swing.JComboBox<>();
        DescTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TotalTF = new javax.swing.JTextField();
        ListBTN = new javax.swing.JButton();
        CalBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CalBTN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 255, 0)));

        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Item Costing");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Item Code :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Bom ID :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Description :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material ID", "Name", "Qty", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        IcodeCMB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        IcodeCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IcodeCMBActionPerformed(evt);
            }
        });

        BomIdCMB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        DescTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Total cost of the Item :");

        TotalTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TotalTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalTFActionPerformed(evt);
            }
        });

        ListBTN.setBackground(new java.awt.Color(0, 0, 0));
        ListBTN.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        ListBTN.setForeground(new java.awt.Color(255, 255, 255));
        ListBTN.setText("List");
        ListBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListBTNActionPerformed(evt);
            }
        });

        CalBTN.setBackground(new java.awt.Color(0, 0, 0));
        CalBTN.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        CalBTN.setForeground(new java.awt.Color(255, 255, 255));
        CalBTN.setText("Calculate");
        CalBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalBTNActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/source.gif"))); // NOI18N

        CalBTN1.setBackground(new java.awt.Color(0, 0, 0));
        CalBTN1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        CalBTN1.setForeground(new java.awt.Color(255, 255, 255));
        CalBTN1.setText("Back");
        CalBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(ListBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IcodeCMB, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(BomIdCMB, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DescTF, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(CalBTN)
                        .addGap(52, 52, 52)
                        .addComponent(CalBTN1)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(481, 481, 481))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(TotalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IcodeCMB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(BomIdCMB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DescTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(ListBTN)
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TotalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalBTN1)
                    .addComponent(CalBTN))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListBTNActionPerformed
        // TODO add your handling code here:
        BomIdCMB.removeAllItems();
        try{
           
            ResultSet rs = new DBSearch().SearchBom("Select Description From Item WHERE Icode = '"+IcodeCMB.getSelectedItem()+"'");
            while(rs.next()) {
                DescTF.setText(rs.getString("Description"));
            
            ResultSet rs1 = new DBSearch().SearchBom("Select BomId From Bom WHERE Icode = '"+IcodeCMB.getSelectedItem()+"'");
            while(rs1.next()) {
                BomIdCMB.addItem(rs1.getString("BomId"));
            }
        } 
    }                                         
            catch(Exception e){
                e.printStackTrace();
        }
    }//GEN-LAST:event_ListBTNActionPerformed

    private void CalBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalBTNActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            ResultSet rs2 = new DBSearch().SearchItem("SELECT MatId,Qty from BomTrans where BomId ='"+BomIdCMB.getSelectedItem()+"' AND Icode = '"+IcodeCMB.getSelectedItem()+"'");
            
            DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
            Vector v = null;
            float totValue=0f;
           while(rs2.next())
           {
               String Mid=rs2.getString("MatId");
               String Qty=rs2.getString("Qty");
              // String Qty = tn.nextToken();
               int q=Integer.parseInt(Qty);
               ResultSet rs3 = new DBSearch().SearchItem("SELECT Price,MatName from Material where MatId = '"+Mid+"'");
              while(rs3.next())
              {
               v = new Vector();
               v.add(Mid);
               String Price=rs3.getString("Price");
               float p=Float.parseFloat(Price);
               v.add(rs3.getString("MatName"));
               v.add(Qty);
               v.add(Price);
               dtm.addRow(v);
               float itemprice=p*q;
               totValue+=itemprice;
               
              }
           } 
           TotalTF.setText(totValue+"");

        } catch (Exception e) {
             Logger.getLogger(ItemCosting.class.getName()).log(Level.SEVERE, null, e);
        }
    }                                       

    public void SearchCode(){
        try{
            ResultSet rs = new DBSearch().SearchCode("Select Icode From Item");
            while(rs.next()) {
                IcodeCMB.addItem(rs.getString("Icode"));
            }
        }
        catch(Exception e){
            e.printStackTrace();
        } 
    }//GEN-LAST:event_CalBTNActionPerformed

    private void CalBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalBTN1ActionPerformed
        // TODO add your handling code here:
        ItemCosting.getFrames()[1].dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_CalBTN1ActionPerformed

    private void TotalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalTFActionPerformed

    private void IcodeCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IcodeCMBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IcodeCMBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemCosting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemCosting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemCosting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemCosting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemCosting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BomIdCMB;
    private javax.swing.JButton CalBTN;
    private javax.swing.JButton CalBTN1;
    private javax.swing.JTextField DescTF;
    private javax.swing.JComboBox<String> IcodeCMB;
    private javax.swing.JButton ListBTN;
    private javax.swing.JTextField TotalTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
