/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AllController;
import Model.DBSearch;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Nadeesha
 */
public class Reorder extends javax.swing.JFrame {

    /**
     * Creates new form Reorder
     */
    
    String req;
    String ava;
    int rOrder;
    public Reorder() {
        initComponents();
        
        SearchMid();
        SearchSup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SupOIdTF = new javax.swing.JTextField();
        AddBTN = new javax.swing.JButton();
        CalBTN = new javax.swing.JButton();
        OrderBTN = new javax.swing.JButton();
        SupIdCMB = new javax.swing.JComboBox<>();
        ReoQtyTF = new javax.swing.JTextField();
        MatIdCMB = new javax.swing.JComboBox<>();
        AstockTF = new javax.swing.JTextField();
        RstockTF = new javax.swing.JTextField();
        LtimeTF = new javax.swing.JTextField();
        HcostTF = new javax.swing.JTextField();
        OcostTF = new javax.swing.JTextField();
        ScostTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 255, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Material Order/ Reorder");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 30, 485, 70);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Supplier OID :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(42, 124, 160, 28);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Material ID :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(42, 173, 150, 28);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Available Stock :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(42, 224, 170, 28);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Required Stock :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(42, 281, 170, 28);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Lead Time :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(42, 339, 140, 28);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Holding Cost :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(42, 395, 150, 28);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("Odering Cost :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(42, 458, 150, 28);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("Shortage Cost :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(42, 517, 160, 28);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText("Reorder Qty :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 680, 150, 28);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setText("Supplier ID :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 750, 140, 28);

        SupOIdTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(SupOIdTF);
        SupOIdTF.setBounds(200, 130, 155, 28);

        AddBTN.setBackground(new java.awt.Color(0, 0, 0));
        AddBTN.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        AddBTN.setForeground(new java.awt.Color(255, 255, 255));
        AddBTN.setText("Add");
        AddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBTNActionPerformed(evt);
            }
        });
        jPanel1.add(AddBTN);
        AddBTN.setBounds(440, 160, 73, 37);

        CalBTN.setBackground(new java.awt.Color(0, 0, 0));
        CalBTN.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        CalBTN.setForeground(new java.awt.Color(255, 255, 255));
        CalBTN.setText("Calculate");
        CalBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalBTNActionPerformed(evt);
            }
        });
        jPanel1.add(CalBTN);
        CalBTN.setBounds(76, 589, 129, 37);

        OrderBTN.setBackground(new java.awt.Color(0, 0, 0));
        OrderBTN.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        OrderBTN.setForeground(new java.awt.Color(255, 255, 255));
        OrderBTN.setText("Place the Order");
        OrderBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderBTNActionPerformed(evt);
            }
        });
        jPanel1.add(OrderBTN);
        OrderBTN.setBounds(230, 800, 189, 37);

        SupIdCMB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(SupIdCMB);
        SupIdCMB.setBounds(190, 750, 130, 30);

        ReoQtyTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(ReoQtyTF);
        ReoQtyTF.setBounds(200, 682, 130, 30);

        MatIdCMB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(MatIdCMB);
        MatIdCMB.setBounds(190, 180, 120, 28);

        AstockTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(AstockTF);
        AstockTF.setBounds(220, 230, 150, 28);

        RstockTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(RstockTF);
        RstockTF.setBounds(220, 280, 150, 28);

        LtimeTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LtimeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LtimeTFActionPerformed(evt);
            }
        });
        jPanel1.add(LtimeTF);
        LtimeTF.setBounds(180, 340, 150, 28);

        HcostTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(HcostTF);
        HcostTF.setBounds(200, 400, 130, 28);

        OcostTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(OcostTF);
        OcostTF.setBounds(200, 460, 140, 28);

        ScostTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(ScostTF);
        ScostTF.setBounds(200, 520, 140, 28);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/9.jpg"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 550, 240, 330);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 800, 83, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/7.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(360, 330, 210, 210);
        jPanel1.add(jLabel14);
        jLabel14.setBounds(430, 430, 90, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LtimeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LtimeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LtimeTFActionPerformed

    private void AddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBTNActionPerformed
        // TODO add your handling code here:
        try{
ResultSet rs = new DBSearch().SearchMid("SELECT SQty FROM Material WHERE MatId='"+MatIdCMB.getSelectedItem()+"'");
            while(rs.next()) {
                AstockTF.setText(rs.getString("SQty"));
                ava = rs.getString("SQty");
            }
ResultSet rs1 = new DBSearch().SearchBom("SELECT RQty FROM AvailableOrder WHERE MatId='"+MatIdCMB.getSelectedItem()+"'");
                while(rs1.next()){
                RstockTF.setText(rs1.getString("RQty"));
                req = rs1.getString("RQty");
                }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_AddBTNActionPerformed

    private void CalBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalBTNActionPerformed
        // TODO add your handling code here:
       
        int ordercost = Integer.parseInt(OcostTF.getText().toString().trim());
        int holdcost = Integer.parseInt(HcostTF.getText().toString().trim());
         int rQty =Integer.parseInt(req);
         int aQty =Integer.parseInt(ava);
        /* try{
         ResultSet rs2 = new DBSearch().SearchMid("SELECT SQty from Material where MatId = '"+MatIdCMB.getSelectedItem()+"'");
            int reOrder = 0;
         while(rs2.next()){
                  String SQty=rs2.getString("SQty");
                  int rQty =Integer.parseInt(req);
                  
        ResultSet rs3 = new DBSearch().SearchBom("SELECT RQty FROM AvailableOrder WHERE MatId='"+MatIdCMB.getSelectedItem()+"'");
                while(rs3.next()){
                String RQty=rs2.getString("RQty");
                  int aQty =Integer.parseInt(ava);*/
                  
          
             EOQ(ordercost, holdcost, rQty, aQty);
       // float e = (2*(R*200)*o)/h;
        ////int eoq = (int) Math.sqrt(e);
       // int rOrder = (eoq - S);
       // reOrder += rOrder;
       // rOrder = Integer.valueOf(reOrder);
                  
              /*  }
              }
               
        }
        catch(Exception e){
            e.printStackTrace();
        }*/
        
       
    }//GEN-LAST:event_CalBTNActionPerformed

    private void OrderBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderBTNActionPerformed
        // TODO add your handling code here:
        String MatId = MatIdCMB.getSelectedItem().toString();
        String SupplierId= SupIdCMB.getSelectedItem().toString();
        AllController.SupplierOrder(SupOIdTF.getText(),MatId, SupplierId,ReoQtyTF.getText());
         //JOptionPane.showMessageDialog(null,"New REcord has been inserted", "Successfully", JOptionPane.INFORMATION_MESSAGE);
        ClearField();
    }                                        
    void EOQ(int o,int h, int r, int a){
        float e = (2*(r*200)*o)/h;
        int eoq = (int) Math.sqrt(e);
        int reOrder = (eoq - a);
         ReoQtyTF.setText(reOrder+"");
         reOrder = Integer.valueOf(reOrder);
    }//GEN-LAST:event_OrderBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Reorder.getFrames()[1].dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void SearchMid(){
        
        try{
           
            ResultSet rs = new DBSearch().SearchMid("Select * From Material");
            
            while(rs.next()) {
                MatIdCMB.addItem(rs.getString("MatId"));
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
   
    public void SearchSup(){
        
        try{
           
            ResultSet rs = new DBSearch().SearchSup("Select * From Supplier");
            
            while(rs.next()) {
                SupIdCMB.addItem(rs.getString("SupplierId"));
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reorder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBTN;
    private javax.swing.JTextField AstockTF;
    private javax.swing.JButton CalBTN;
    private javax.swing.JTextField HcostTF;
    private javax.swing.JTextField LtimeTF;
    private javax.swing.JComboBox<String> MatIdCMB;
    private javax.swing.JTextField OcostTF;
    private javax.swing.JButton OrderBTN;
    private javax.swing.JTextField ReoQtyTF;
    private javax.swing.JTextField RstockTF;
    private javax.swing.JTextField ScostTF;
    private javax.swing.JComboBox<String> SupIdCMB;
    private javax.swing.JTextField SupOIdTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void ClearField() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
